// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqMUa27Wh479cS5Q-MsLpakI3C9sOmm5U',
    appId: '1:719819794534:web:7be257127a609a3c2ee5a7',
    messagingSenderId: '719819794534',
    projectId: 'time-tracker-app-64906',
    authDomain: 'time-tracker-app-64906.firebaseapp.com',
    storageBucket: 'time-tracker-app-64906.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc6L3Hvb05BI_GAN17-AJnyYgs5eerA2I',
    appId: '1:719819794534:android:6f6f1790d131c5632ee5a7',
    messagingSenderId: '719819794534',
    projectId: 'time-tracker-app-64906',
    storageBucket: 'time-tracker-app-64906.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7S8dKnNijXNGiaDQnKJtDMHTHZfcI4Jo',
    appId: '1:719819794534:ios:231a48a44dd7d32b2ee5a7',
    messagingSenderId: '719819794534',
    projectId: 'time-tracker-app-64906',
    storageBucket: 'time-tracker-app-64906.appspot.com',
    iosClientId: '719819794534-88iresa9g3mqsaambc05gi082o6nibf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7S8dKnNijXNGiaDQnKJtDMHTHZfcI4Jo',
    appId: '1:719819794534:ios:231a48a44dd7d32b2ee5a7',
    messagingSenderId: '719819794534',
    projectId: 'time-tracker-app-64906',
    storageBucket: 'time-tracker-app-64906.appspot.com',
    iosClientId: '719819794534-88iresa9g3mqsaambc05gi082o6nibf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeTrackerApp',
  );
}
